import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <div>
            <Header />

            <main className="container min-h-screen mx-auto px-4 max-w-6xl">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
