name: Migrate
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: environment variables
        run: env
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      # - run: npm run build
      - name: Apply all pending migrations to the database
        if: ${{ env.POSTGRES_PRISMA_URL }}
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
